const TILE_SIZE = 256
const EARTH_RADIUS = 6378137
const EARTH_DIAMETER = EARTH_RADIUS * 2
const EARTH_CIRCUMFERENCE = EARTH_DIAMETER * Math.PI
const ORIGIN_SHIFT = EARTH_CIRCUMFERENCE / 2

module.exports = {
  TILE_SIZE,
  EARTH_RADIUS,
  EARTH_DIAMETER,
  EARTH_CIRCUMFERENCE,
  ORIGIN_SHIFT
}
